"""Domain kernel for "Autenticación JWT y Serialización Transaccional en Django REST Framework" (generated by gherkin-ai).

Pure domain logic: no framework, no I/O. Extend the command handlers with your business rules.
"""
from __future__ import annotations

from dataclasses import dataclass, field
from datetime import datetime, timezone
from enum import Enum
from typing import Any, Dict, List

__all__ = [
    "DomainValidationError",
    "AutenticacionJwtYSerializacionTransaccionalEnDjangoRestFrameworkState",
    "AutenticacionJwtYSerializacionTransaccionalEnDjangoRestFrameworkEventType",
    "AutenticacionJwtYSerializacionTransaccionalEnDjangoRestFrameworkCommand",
    "AutenticacionJwtYSerializacionTransaccionalEnDjangoRestFrameworkDomainEvent",
    "AutenticacionJwtYSerializacionTransaccionalEnDjangoRestFrameworkAggregate",
]


class DomainValidationError(ValueError):
    """Raised when a command or aggregate violates a domain invariant."""


class AutenticacionJwtYSerializacionTransaccionalEnDjangoRestFrameworkState(str, Enum):
    PENDING = "PENDING"


class AutenticacionJwtYSerializacionTransaccionalEnDjangoRestFrameworkEventType(str, Enum):
    ProcessAutenticacionJwtYSerializacionTransaccionalEnDjangoRestFrameworkCompleted = "ProcessAutenticacionJwtYSerializacionTransaccionalEnDjangoRestFrameworkCompleted"
    AutenticacionJwtYSerializacionTransaccionalEnDjangoRestFrameworkProcessed = "AutenticacionJwtYSerializacionTransaccionalEnDjangoRestFrameworkProcessed"


@dataclass(frozen=True)
class AutenticacionJwtYSerializacionTransaccionalEnDjangoRestFrameworkCommand:
    id: str
    payload: Dict[str, Any] = field(default_factory=dict)


@dataclass(frozen=True)
class AutenticacionJwtYSerializacionTransaccionalEnDjangoRestFrameworkDomainEvent:
    type: AutenticacionJwtYSerializacionTransaccionalEnDjangoRestFrameworkEventType
    aggregate_id: str
    version: int
    occurred_on: datetime
    payload: Dict[str, Any]


class AutenticacionJwtYSerializacionTransaccionalEnDjangoRestFrameworkAggregate:
    def __init__(self, id: str) -> None:
        if not id or not id.strip():
            raise DomainValidationError("AutenticacionJwtYSerializacionTransaccionalEnDjangoRestFramework id is required")
        self.id = id
        self.state = AutenticacionJwtYSerializacionTransaccionalEnDjangoRestFrameworkState.PENDING
        self.version = 0
        self._pending_events: List[AutenticacionJwtYSerializacionTransaccionalEnDjangoRestFrameworkDomainEvent] = []

    @classmethod
    def restore(cls, id: str, state: AutenticacionJwtYSerializacionTransaccionalEnDjangoRestFrameworkState, version: int) -> "AutenticacionJwtYSerializacionTransaccionalEnDjangoRestFrameworkAggregate":
        """Rebuilds an aggregate from persisted state; no events are recorded."""
        aggregate = cls(id)
        aggregate.state = state
        aggregate.version = version
        return aggregate

    @property
    def pending_events(self) -> List[AutenticacionJwtYSerializacionTransaccionalEnDjangoRestFrameworkDomainEvent]:
        """Events recorded since the aggregate was loaded (to be saved via the outbox)."""
        return list(self._pending_events)

    def process_autenticacion_jwt_y_serializacion_transaccional_en_django_rest_framework(self, command: AutenticacionJwtYSerializacionTransaccionalEnDjangoRestFrameworkCommand) -> AutenticacionJwtYSerializacionTransaccionalEnDjangoRestFrameworkDomainEvent:
        self._assert_valid(command)
        return self._record(AutenticacionJwtYSerializacionTransaccionalEnDjangoRestFrameworkEventType.ProcessAutenticacionJwtYSerializacionTransaccionalEnDjangoRestFrameworkCompleted, command.payload)

    def _assert_valid(self, command: AutenticacionJwtYSerializacionTransaccionalEnDjangoRestFrameworkCommand) -> None:
        if command is None or not command.id or not command.id.strip():
            raise DomainValidationError("Command id is required")
        if command.id != self.id:
            raise DomainValidationError(f"Command targets {command.id}, not {self.id}")

    def _record(self, type_: AutenticacionJwtYSerializacionTransaccionalEnDjangoRestFrameworkEventType, payload: Dict[str, Any]) -> AutenticacionJwtYSerializacionTransaccionalEnDjangoRestFrameworkDomainEvent:
        self.version += 1
        event = AutenticacionJwtYSerializacionTransaccionalEnDjangoRestFrameworkDomainEvent(type_, self.id, self.version, datetime.now(timezone.utc), dict(payload or {}))
        self._pending_events.append(event)
        return event
