"""pytest-bdd step definitions for "Autenticación JWT y Serialización Transaccional en Django REST Framework" (generated by gherkin-ai).

Every scenario in the feature runs as a test. Steps are pending: they skip until implemented.
"""
import pytest
from pytest_bdd import given, scenarios, then, when

from app.domain import AutenticacionJwtYSerializacionTransaccionalEnDjangoRestFrameworkAggregate

scenarios("features/django_drf_transaction.feature")


@pytest.fixture
def aggregate():
    return AutenticacionJwtYSerializacionTransaccionalEnDjangoRestFrameworkAggregate("scenario-aggregate")


@given("que un usuario envía credenciales a `/api/token/` y obtiene un `access_token`")
def given_que_un_usuario_envia_credenciales_a_api_token_y_obtiene_un_access_token(aggregate):
    # Pending: drive the aggregate (or the HTTP API) and assert the outcome.
    pytest.skip("Pending step: implement it, then remove this line")


@when("realiza un POST a `/api/v1/orders/` enviando el `CreateOrderRequestContract`")
def when_realiza_un_post_a_api_v1_orders_enviando_el_create_order_request_contract(aggregate):
    # Pending: drive the aggregate (or the HTTP API) and assert the outcome.
    pytest.skip("Pending step: implement it, then remove this line")


@then("el Serializer de DRF realiza la validación de tipos y de idempotencia")
def then_el_serializer_de_drf_realiza_la_validacion_de_tipos_y_de_idempotencia(aggregate):
    # Pending: drive the aggregate (or the HTTP API) and assert the outcome.
    pytest.skip("Pending step: implement it, then remove this line")


@then("Pytest-django ejecuta la suite de pruebas comprobando el estado HTTP 201 Created")
def then_pytest_django_ejecuta_la_suite_de_pruebas_comprobando_el_estado_http_201_cr(aggregate):
    # Pending: drive the aggregate (or the HTTP API) and assert the outcome.
    pytest.skip("Pending step: implement it, then remove this line")


@then("la vista en React mediante `useMutation` actualiza el estado del dashboard")
def then_la_vista_en_react_mediante_use_mutation_actualiza_el_estado_del_dashboard(aggregate):
    # Pending: drive the aggregate (or the HTTP API) and assert the outcome.
    pytest.skip("Pending step: implement it, then remove this line")
