# ==========================================================================
# Generated Domain Contracts & Pydantic DTO Schemas
# Feature: Autenticación JWT y Serialización Transaccional en Django REST Framework
# Stack: Python + django + sqlalchemy
# Generated by gherkin-ai CLI v3.0.0
# ==========================================================================

from datetime import datetime
from typing import Protocol, Any, Dict, Optional
from pydantic import BaseModel, Field, UUID4

# --------------------------------------------------------------------------
# 1. Base Domain Event & Event Schemas
# --------------------------------------------------------------------------
class IDomainEvent(BaseModel):
    event_id: UUID4
    occurred_on: datetime = Field(default_factory=datetime.utcnow)
    event_type: str



# --------------------------------------------------------------------------
# 2. Command DTO Schema (Pydantic v2 Validation)
# --------------------------------------------------------------------------
class AutenticacionJwtYSerializacionTransaccionalEnDjangoRestFrameworkCommand(BaseModel):
    request_id: UUID4
    timestamp: datetime = Field(default_factory=datetime.utcnow)
    payload: Dict[str, Any]

# --------------------------------------------------------------------------
# 3. Domain Repository Port (Outbound Protocol)
# --------------------------------------------------------------------------
class IAutenticacionJwtYSerializacionTransaccionalEnDjangoRestFrameworkRepository(Protocol):
    async def find_by_id(self, entity_id: str) -> Optional[Any]:
        ...

    async def save(self, entity: Any) -> None:
        ...

    async def delete(self, entity_id: str) -> None:
        ...

# --------------------------------------------------------------------------
# 4. Application Event Publisher Port
# --------------------------------------------------------------------------
class IEventPublisher(Protocol):
    async def publish(self, event: IDomainEvent) -> None:
        ...
