/* ==========================================================================
   Generated Test Fixtures & Seed Setup
   Feature: Autenticación JWT y Serialización Transaccional en Django REST Framework
   Generated by gherkin-ai CLI
   ========================================================================== */

export interface AutenticacionJwtYSerializacionTransaccionalEnDjangoRestFrameworkFixture {
  id: string;

}

export function createAutenticacionJwtYSerializacionTransaccionalEnDjangoRestFrameworkFixture(): AutenticacionJwtYSerializacionTransaccionalEnDjangoRestFrameworkFixture {
  return {
    id: 'f47ac10b-58cc-4372-a567-0e02b2c3d479',

  };
}

export const GHERKIN_GIVEN_PRECONDITIONS = [
  "que un usuario envía credenciales a `/api/token/` y obtiene un `access_token`"
];
