"""Minimal in-process event bus used by sagas to dispatch commands (generated by gherkin-ai).

Replace or bridge it to your broker (RabbitMQ, Kafka, SQS), ideally through the transactional outbox.
"""
from collections import defaultdict
from typing import Any, Callable, Dict, List

Handler = Callable[[Dict[str, Any]], None]


class EventBus:
    def __init__(self) -> None:
        self._handlers: Dict[str, List[Handler]] = defaultdict(list)
        self.published: List[tuple] = []

    def subscribe(self, name: str, handler: Handler) -> None:
        self._handlers[name].append(handler)

    def publish(self, name: str, payload: Dict[str, Any]) -> None:
        self.published.append((name, payload))
        for handler in self._handlers.get(name, []):
            handler(payload)


event_bus = EventBus()
