"""DRF API executing the domain kernel commands (generated by gherkin-ai)."""
from rest_framework.decorators import api_view
from rest_framework.response import Response

from app.domain import AutenticacionJwtYSerializacionTransaccionalEnDjangoRestFrameworkAggregate, AutenticacionJwtYSerializacionTransaccionalEnDjangoRestFrameworkCommand, DomainValidationError
from app.outbox import save_pending_events

_COMMANDS = {
    "process_autenticacion_jwt_y_serializacion_transaccional_en_django_rest_framework": AutenticacionJwtYSerializacionTransaccionalEnDjangoRestFrameworkAggregate.process_autenticacion_jwt_y_serializacion_transaccional_en_django_rest_framework,
}


@api_view(["GET"])
def health(request):
    return Response({"status": "ok"})


@api_view(["POST"])
def execute(request, aggregate_id: str, command: str):
    handler = _COMMANDS.get(command)
    if handler is None:
        return Response({"detail": f"Unknown command {command}"}, status=404)
    aggregate = AutenticacionJwtYSerializacionTransaccionalEnDjangoRestFrameworkAggregate(aggregate_id)
    try:
        event = handler(aggregate, AutenticacionJwtYSerializacionTransaccionalEnDjangoRestFrameworkCommand(aggregate_id, dict(request.data or {})))
    except DomainValidationError as err:
        return Response({"detail": str(err)}, status=422)
    save_pending_events(aggregate)
    return Response({"type": event.type.value, "aggregateId": event.aggregate_id, "version": event.version}, status=201)
